---
- name: install Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.yum:
        name:
          - mysql
        state: latest
        update_cache: true

    - name: Start Mysql
      ansible.builtin.service:
        name: "mysql"
        enabled: true
        state: started
